node {
   def commit_id
   stage('step pre') {
     checkout scm
     sh "git rev-parse --short HEAD > .git/commit-id"                        
     commit_id = readFile('.git/commit-id').trim()
   }
   stage('test') {
     nodejs(nodeJSInstallationName: 'NodeJS') {
       dir("basics"){
       sh 'npm install --only=dev'
       sh 'npm test'
       }
     }
   }
   stage('docker build/push') {
     docker.withRegistry('https://index.docker.io/v1/', '0399a7cb-12f4-4acd-bcd4-5e691eb4652f') {
       def app = docker.build("ofirtasa/docker-nodejs-demo:${commit_id}", '.').push()
     }
   }
   stage('docker run') {
     sh label: '', script: '''
      docker run --rm -tid --name docker_test -p 3000 yanivomc/docker-nodejs-demo:latest
      docker kill docker_test
      
      '''
     }
   }

